#configuration file

model_name: 'srdense'
exp_name: 'srdense_train_mse_ssim_axis2'
# exp_name: 'srdense_avg_image_train_mse_ssim_derivative_loss'
project_name: 'super_resolution'
wandb: True 
 

lr: 0.0001
train_batch_size: 16
val_batch_size: 1

train_hr_array_path: '../3D_Training/data_array/25/f1_25.nii'
train_lr_array_path: '../3D_Training/data_array/50/f1_50.nii'
axis: 2

factor: 2
# criterions: ['mse','laplace pyramid'] 
criterions: ['mse','ssim'] 

num_epochs: 1505
lr: 0.0001
lr_decay_factor: 0.98
original_lr: 0.001

n_freq: 50 # model checkpoint saving frequency

train_batch_size: 16
val_batch_size: 1
seed: 34

init: 'norm' 
optimizer: sgd
momentum: 0.9
weight_decay: 0.1

growth_rate: 3
num_blocks: 4
num_layers: 3

description: 'this experiment is carried out with larger model and using larger kernel and deeper level and sigma 1.5 for laplacian pyramid loss'


